name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          backend/node_modules
          frontend/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install backend dependencies
      run: npm install
      working-directory: backend

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Linter Frontend
      run: npm run lint:fix
      working-directory: frontend

    - name: Jest Backend
      env:
        MONGODB_DBNAME: aura_TEST
        MONGODB_PW: ${{ secrets.DB_PASSWORD }}
        
      working-directory: backend
      run:
        npm run start:test
        npm test
