name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Super Linter on backend
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
      working-directory: backend
      run:
        npm install
        npm run lint

    - name: Jest on backend
      env:
        MONGODB_URI: mongodb+srv://pensano-aura-db-user:${{ secrets.DB_PASSWORD }}@cluster0.sylisri.mongodb.net/aura-DEV
      working-directory: backend
      run:
        npm start
        npm run test

    - name: Super Linter on frontend
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
      working-directory: frontend
      run:
        npm install
        npm run lint
