name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Super Linter for backend
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
      working-directory: backend
      run:
        npm install
        npm run lint

    - name: Jest for backend
      working-directory: backend
      run:
        npm run test

    - name: Super Linter for frontend
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
      working-directory: frontend
      run:
        npm install
        npm run lint
