name: CI Pipeline

env:
  VALIDATE_ALL_CODEBASE: true
  DEFAULT_BRANCH: main
  MONGODB_URI: mongodb+srv://pensano-aura-db-user:${{ secrets.DB_PASSWORD }}@cluster0.sylisri.mongodb.net/aura-DEV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install_deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies backend
        working-directory: backend
        run: npm install

      - name: Install dependencies frontend
        working-directory: frontend
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install_deps
    steps:
      - name: Lint frontend
        # working-directory: frontend
        run: |
          npm run lint
