name: API Jest Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Jest globally
      run: npm install -g jest

    - name: Server and tests on backend
      env:
        NODE_ENV: TEST
        MONGODB_DBNAME: aura_TEST
        MONGODB_PW: ${{ secrets.DB_PASSWORD }}
      working-directory: backend
      run:
        npm install && node index.js & sleep 10 && npx jest --detectOpenHandles --forceExit




